version: '3.8'

services:
  web:
    build: ./django_music
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_music/:/django_music/
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Somepass_975
      - POSTGRES_DB=django_music_db

volumes:
  postgres_data: