# Generated by Django 4.1.3 on 2022-11-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_alter_trackalbum_options_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_library.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='trackalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_library.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='trackalbum',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music_library.track', verbose_name='Трек'),
        ),
    ]
